---
- name: Restart DNS
  service:
    name: named
    state: restarted

- name: Restart FW
  service:
    name: firewalld
    state: restarted

- name: Restart TFTP
  service:
    name: tftp
    state: restarted

- name: Restart dnsmasq
  service:
    name: dnsmasq
    state: restarted

- name: Restart DHCP
  service:
    name: dhcpd
    state: restarted

- name: Restart HA
  service:
    name: haproxy
    state: restarted

- name: Stop FW
  service:
    name: firewalld
    state: stopped

- name: Start TFTP
  service:
    name: tftp
    state: started
